apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: imgproc.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /api/images/?(.*)
            pathType: Prefix
            backend:
              serviceName: storage-srv
              servicePort: 3000
          - path: /api/transform/?(.*)
            pathType: Prefix
            backend:
              serviceName: image-processor-srv
              servicePort: 3000