apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args: [
              '-p',  ## port
              '4222',
              '-m', ## health check port
              '8222',
              '-hbi', ## heartbeat interval
              '5s', ## - every 5s make requst to pub/sub clients to check if alive
              '-hbt', # how much time given to respond
              '5s',
              '-hbf', ## how many fails until client considered dead
              '2',
              '-SD',
              '-cid',
              'imgproc',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring # for healthchecks
      protocol: TCP
      port: 8222
      targetPort: 8222
