name: tests-metadata

on:
  pull_request:
    paths:
      - 'metadata/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # copy project
      - run: cd metadata && npm install && npm run test:ci

